development:
  host: localhost
  port: 27017
  database: blog_dev
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: blog_prod
  logfile: production.log
    
environment: development